### ISSUE TITLE
Consider using Murmur3 instead of SHA in VariationOrRollout

### ISSUE THREAD

**Issue by rbalamohan** [launchdarkly/java-client#120]
https://github.com/launchdarkly/java-client/blob/master/src/main/java/com/launchdarkly/client/VariationOrRollout.java#L51

VariationOrRollout is one of the hotpath code and it internally uses SHA1  for computing hash. SHA1 is CPU intensive and is outdated as well. It would be good to consider using other hashing functions like murmur3 which is fairly CPU optimised. Guava libraries should have murmur3 IIRC.

**Comment by eli-darkly** [comment]
See PR comments. Summary: we're considering such a change, but it would require server-side changes first. I'm closing this issue since it's not something we can address in the Java SDK by itself, but we're still tracking it as a desirable future feature.
