### ISSUE TITLE
timeout error logged as error

### ISSUE THREAD

**Issue by madgnome** [launchdarkly/java-client#130]
The following is logged at ERROR level and polluting our logs.  If the error can be recovered from we probably shouldn't log it as error.

```
Encountered EventSource error: timeout
```

**Comment by eli-darkly** [comment]
Hi - sorry we've taken a while to get to this. We're changing it in the next release to log these messages as WARN instead.

In the future, we may implement something a little more intelligent such as logging at a lower level but switching to a higher level if the outage lasts longer than X amount of time.

**Comment by eli-darkly** [comment]
OK, version 4.5.1 has been released with this fix.
