### ISSUE TITLE
Make SSE reconnect strategy configurable, with backoff and jitter

### ISSUE THREAD

**Issue by samhaldane** [launchdarkly/java-client#74]
We currently have tens of thousands of clients connecting to a service running ld-relay. If the SSE connection is closed (e.g. because of a proxy restart or network blip) all clients attempt to reconnect once per second, which hammers our ld-relay service. The reconnect strategy should be configurable, and ideally use exponential backoff with a jitter.

**Comment by jkodumal** [comment]
We'll add this to all our SDKs. For the Java and Android SDKs, this will involve picking up a change to the okhttp-eventsource library: launchdarkly/okhttp-eventsource/#7

**Comment by jkodumal** [comment]
This has been added to okhttp-eventsource-- one that's released it we'll need a version bump here, and we'll want to expose a configuration parameter for the reconnection timeout at the LDClient config level.
