### ISSUE TITLE
LDClient#allFlags should not return null if using TestFeatureStore offline

### ISSUE THREAD

**Issue by samhaldane** [launchdarkly/java-client#75]
It would be handy to be able to use the allFlags method in unit tests with TestFeatureStore in offline mode. At the moment the method returns null if the client is in offline mode. Change it to return the result of InMemoryFeatureStore#all in this situation.

**Comment by samhaldane** [comment]
@jkodumal it would be good to get a fix for this one

**Comment by jkodumal** [comment]
@samhaldane On it-- should be a relatively simple one on our end.

**Comment by gjoseph** [comment]
Hey @jkodumal, any chance for an update on this ?

**Comment by drichelson** [comment]
@samhaldane https://github.com/launchdarkly/java-client/pull/81 should address your request. I've published 2.0.7-SNAPSHOT if you want to take a look right away.

**Comment by gjoseph** [comment]
FWIW, I tried this (build a snapshot myself as I wasn't sure where to get yours - https://oss.sonatype.org/content/repositories/snapshots didn't have it - and it worked :)
Any ETA on the actual release ?

**Comment by drichelson** [comment]
HI Sam, We released 2.0.7. Snapshots can be found here: https://oss.sonatype.org/content/groups/public/

**Comment by gjoseph** [comment]
Sweet, thanks Dan!

**Comment by samhaldane** [comment]
Thanks @drichelson
