### ISSUE TITLE
[com.launchdarkly.client.LDClient] should not WARN about unknown feature flags in test mode. 

### ISSUE THREAD

**Issue by luke-esther** [launchdarkly/java-client#84]
When a feature flag cannot be found, the client logs at the WARN level:

Unknown feature flag example-feature-flag-key; returning default value

We find it useful in test mode to rely on the default value for features, and only enable/disable features as required. This means we don't have to configure our application to load a default flag list into the client.

The resulting logging statements are painful, and we would like if they could be suppressed in test mode.

**Comment by drichelson** [comment]
Hi,
Are you able to set the log level to ERROR for the offending class? Most logging frameworks allow you to do this.

**Comment by luke-esther** [comment]
We can, but we will then miss out on any warnings that LDClient provides.

**Comment by drichelson** [comment]
@luke-esther do you mind emailing support@launchdarkly.com and we can continue there?
Thanks

**Comment by wildthing81** [comment]
@drichelson  Apart from changing granularity of Logger class, is there any other way. I also have a feature flag for TEST mode & want to rely on default value for it. don't want to define it in LD portal for all our envs
