### ISSUE TITLE
Add the ability to check for the presence of a flag in the Java client

### ISSUE THREAD

**Issue by yuv422** [launchdarkly/java-client#87]
It would be great if we could use the java client to detect if a flag exists.

We are currently require that flags contain a certain prefix. This is baked into our code. We would now like to relax this restriction and remove the prefix.

eg. **product.some.flag** changes to **some.flag**

Having the ability to query if a flag exists on the client would allow us to seamlessly change our flag key structure to remove the now redundant product prefix without having to change all the existing flag keys. We would simply query the old flag if we detected that the new flag isn't known to the client.

**Comment by jkodumal** [comment]
LGTM-- @drichelson ?

**Comment by arun251** [comment]
Released in 2.1.0.
