### ISSUE TITLE
Better LDUser equality

### ISSUE THREAD

**Issue by igillis** [launchdarkly/java-client#96]
I have a class that wraps LDClient usage. I want to be able to write tests for this class that mock out `LDUserInterface::boolVariation` and `LDUserInterface::allFlags` using Mockito. However, there's no way to set up an argument matcher against LDUser because a) it doesn't implement a useful equals method and b) it doesn't expose any of its state. 

Sample code:
```
LDUser expectedUser = new LDUser.Builder("asdf").custom("foo", 1).build();
when(ldClient.allFlags(eq(expectedUser)).thenReturn(true);
```

**Comment by drichelson** [comment]
Thanks for reaching out @igillis! Would an `equals()` method on LDUser suffice?

**Comment by igillis** [comment]
Yep, that would work. Happy to put up a PR if you want -- not sure what your process looks like.

**Comment by drichelson** [comment]
@igillis we'll do it. I'll have it on your desk by Monday morning at the latest.

**Comment by igillis** [comment]
Awesome :)

**Comment by drichelson** [comment]
@igillis We just release https://github.com/launchdarkly/java-client/releases/tag/2.2.6 which addresses this issue.

**Comment by igillis** [comment]
nice, thanks for the quick turnaround!
